---

- include: "{{role_path}}/../k8s-common/tasks/common.yml"
  vars:
    k8s_manifests_dir: '{{kubedash_manifests_dir}}'
    k8s_resources: '{{kubedash_resources}}'
    k8s_namespace: "{{ kubedash_namespace | default('kube-system') }}"
